apiVersion: v1
kind: Secret
metadata:
  name: server-control-secret
  namespace: server-control
type: Opaque
stringData:
  MONGO_URI: mongodb://mongo:27017/servers
  ILO_USERNAME: change-me
  ILO_PASSWORD: change-me
