apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-control-frontend
  namespace: server-control
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-control-frontend
  template:
    metadata:
      labels:
        app: server-control-frontend
    spec:
      containers:
        - name: frontend
          image: mohamedmedhat646/server-control-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: server-control-frontend
  namespace: server-control
spec:
  selector:
    app: server-control-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
